### ISSUE TITLE
The files linked in Google Colab Tutorials are Broken

### ISSUE THREAD

**Issue by bhishanpdl** [BlazingDB/bsql-demos#26]
I was trying to go through the examples of bsql demos from the website:
https://blazingsql.com/

Following links are broken:
- !wget https://github.com/BlazingDB/bsql-demos/raw/master/utils/colab_env.py
- !wget https://github.com/BlazingDB/bsql-demos/raw/master/utils/bsql-colab.sh

It would be nice if there were correct links.

**Comment by gumdropsteve** [comment]
Hey @bhishanpdl thanks for the issue, sorry you had that experience. We've refocused our demos and have some [new ones here](https://app.blazingsql.com/jupyter/user-redirect/lab/workspaces/auto-b/tree/Welcome_to_BlazingSQL_Notebooks/welcome.ipynb) if you'd be willing to give us another shot?
